### ISSUE TITLE
Crash when tries to install an update from Google Play or update APKUpdater itself

### ISSUE THREAD

**Issue by DeicPro** [rumboalla/apkupdater#200]
The downloaded APKs have got space and no extension, just in case

![screenshot_2017-06-29-01-00-42-171_com android providers downloads ui](https://user-images.githubusercontent.com/12710770/27664187-6e60dd0c-5c66-11e7-8b4c-252df368ac49.png)
![screenshot_2017-06-29-00-56-43-863_com android providers downloads ui](https://user-images.githubusercontent.com/12710770/27664191-762728d4-5c66-11e7-8589-ee5316418a31.png)
![screenshot_2017-06-29-01-02-55-984_com android settings](https://user-images.githubusercontent.com/12710770/27664236-c1e3df42-5c66-11e7-8274-f51914cf1f10.png)

```
java.lang.RuntimeException: Could not dispatch event: class com.apkupdater.event.PackageInstallerEvent to handler [EventHandler public void com.apkupdater.activity.MainActivity_.onPackageInstallerEvent(com.apkupdater.event.PackageInstallerEvent)]: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://downloads/all_downloads/49 typ=application/vnd.android.package-archive flg=0x1 }
	at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
	at com.squareup.otto.Bus.dispatch(Bus.java:387)
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
	at com.squareup.otto.Bus.post(Bus.java:337)
	at com.apkupdater.util.MyBus.access$001(MyBus.java:15)
	at com.apkupdater.util.MyBus$1.run(MyBus.java:34)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5562)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://downloads/all_downloads/49 typ=application/vnd.android.package-archive flg=0x1 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1776)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1496)
	at android.app.Activity.startActivityForResult(Activity.java:3778)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:3739)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at com.apkupdater.activity.MainActivity.onPackageInstallerEvent(MainActivity.java:417)
	at com.apkupdater.activity.MainActivity_.access$101(MainActivity_.java:31)
	at com.apkupdater.activity.MainActivity_.onPackageInstallerEvent(MainActivity_.java:130)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
	at com.squareup.otto.Bus.dispatch(Bus.java:385)
	... 12 more
```

**Comment by rumboalla** [comment]
Fixed in dev branch.
