### ISSUE TITLE
Crash when select hide app

### ISSUE THREAD

**Issue by zekabra** [rumboalla/apkupdater#412]
FATAL EXCEPTION: main
Process: com.apkupdater, PID: 21639
java.lang.IllegalArgumentException: no paragraph
	at b0.k.g(SourceFile:176)
	at p1.d0.b(SourceFile:32)
	at p1.w0.N0(SourceFile:50)
	at p1.w0.L0(SourceFile:25)
	at p1.v.g1(SourceFile:6)
	at p1.w0.N0(SourceFile:8)
	at q.r0.a(SourceFile:90)
	at q.r0.o(SourceFile:123)
	at f0.z.e(SourceFile:59)
	at t0.y.a(SourceFile:48)
	at t0.z.c(SourceFile:66)
	at p1.h1.a(SourceFile:1)
	at p1.w0.v0(SourceFile:28)
	at androidx.compose.ui.platform.c2.h(SourceFile:24)
	at androidx.compose.ui.platform.e2.g(SourceFile:40)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:66)
	at android.view.View.draw(View.java:23279)
	at android.view.View.updateDisplayListIfDirty(View.java:22143)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22099)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22099)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22099)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22099)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4787)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4498)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3685)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2369)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9309)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7930)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)

**Comment by rumboalla** [comment]
Is this in normal or tv ui?
Any way to reproduce? Does it happen with any specific app?

**Comment by zekabra** [comment]
> Is this in normal or tv ui? Any way to reproduce? Does it happen with any specific app?

In normal mode it seems to happen randomly, at least I haven't been able to pinpoint a cause yet

**Comment by parasiteoflife** [comment]
Had the same crash when I was hidding apps too, btw the app becomes laggy when I scroll. I have 400+ apps listed in the app.

Android 12

```
FATAL EXCEPTION: main
Process: com.apkupdater, PID: 7178
java.lang.IllegalArgumentException: no paragraph
	at c0.k.f(SourceFile:174)
	at r1.d0.b(SourceFile:32)
	at r1.w0.A0(SourceFile:50)
	at r1.w0.z0(SourceFile:25)
	at r1.v.T0(SourceFile:6)
	at r1.w0.A0(SourceFile:8)
	at r.r0.a(SourceFile:90)
	at r.r0.m(SourceFile:123)
	at g0.z.e(SourceFile:59)
	at v0.y.a(SourceFile:48)
	at v0.z.c(SourceFile:66)
	at r1.i1.a(SourceFile:1)
	at r1.w0.k0(SourceFile:28)
	at androidx.compose.ui.platform.f2.j(SourceFile:24)
	at androidx.compose.ui.platform.h2.f(SourceFile:40)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(SourceFile:66)
	at android.view.View.draw(View.java:22707)
	at android.view.View.updateDisplayListIfDirty(View.java:21579)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4512)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4485)
	at android.view.View.updateDisplayListIfDirty(View.java:21535)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:616)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4529)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4249)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3372)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2177)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8803)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:780)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7833)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

The app crashes every time I hide 2 to 4 apps in a row.

**Comment by parasiteoflife** [comment]
I just changed the column number in portrait mode to 1 and now it seems the crash is gone.
